# Generated by Django 4.2.1 on 2023-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_translation',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_diploma_translation',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
