# Generated by Django 4.2.1 on 2023-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_student_country_student_entrance_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, choices=[('Андижан', 'Андижан'), ('Бухара', 'Бухара'), ('Фергана', 'Фергана'), ('Жиззах', 'Жиззах'), ('Республика Каракалпакстан', 'Республика Каракалпакстан'), ('Кашкадаря', 'Кашкадаря'), ('Хараезм', 'Харезм'), ('Наманган', 'Наманган'), ('Наваи', 'Наваи'), ('Самарканд', 'Самарканд'), ('Сирдаря', 'Сирдаря'), ('Сурхандаря', 'Сурхандаря'), ('город Ташкент', 'город Ташкент'), ('Ташкентский регион', 'Ташкентский регион')], max_length=100, null=True),
        ),
    ]
