# Generated by Django 4.2.1 on 2023-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_alter_student_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=50, null=True),
        ),
    ]
