# Generated by Django 4.2.1 on 2023-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_remove_student_address_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
