# Generated by Django 4.2.1 on 2023-05-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_alter_student_country_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_2',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
