# Generated by Django 4.2.1 on 2023-05-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_alter_student_email_alter_student_entrance_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
