# Generated by Django 4.2.1 on 2023-05-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_series',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
