# Generated by Django 4.2.1 on 2023-05-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_series',
            field=models.CharField(max_length=9),
        ),
    ]
