# Generated by Django 4.2.1 on 2023-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_alter_student_email_alter_student_passport_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entrance_agreement',
            field=models.FileField(blank=True, null=True, upload_to='entrance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='info_check_agreement',
            field=models.FileField(blank=True, null=True, upload_to='info'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='passport'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_translation',
            field=models.FileField(blank=True, null=True, upload_to='passport_n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_diploma',
            field=models.FileField(blank=True, null=True, upload_to='diploma'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_diploma_translation',
            field=models.FileField(blank=True, null=True, upload_to='diploma_n'),
        ),
    ]
