# Generated by Django 4.2.1 on 2023-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_alter_student_entrance_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='edu_field',
            field=models.CharField(choices=[('', 'Выберите направление обучения'), ('Химическая технология', 'Химическая технология'), ('Техносферная безопасность', 'Техносферная безопасность'), ('Материаловедение и технологии материалов', 'Материаловедение и технологии материалов'), ('Технология художественной обработки материалов', 'Технология художественной обработки материалов'), ('Менеджмент', 'Менеджмент'), ('Химическая технология', 'Химическая технология'), ('Материаловедение и технологии материалов', 'Материаловедение и технологии материалов'), ('Наноматериалы', 'Наноматериалы')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='edu_level',
            field=models.CharField(choices=[('', 'Выберите уровень обучения'), ('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='edu_type',
            field=models.CharField(choices=[('', 'Выберите форму обучения'), ('Очная', 'Очная'), ('Заочная', 'Заочная')], max_length=10, null=True),
        ),
    ]
