# Generated by Django 4.2.1 on 2023-05-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_student_edu_field_student_edu_level_student_edu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='edu_field',
            field=models.CharField(choices=[('', 'Выберите направление обучения'), ('Химическая технология', 'Химическая технология'), ('Техносферная безопасность', 'Техносферная безопасность'), ('Технология художественной обработки материалов', 'Технология художественной обработки материалов'), ('Материаловедение и технологии материалов', 'Материаловедение и технологии материалов'), ('Наноматериалы', 'Наноматериалы')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_level',
            field=models.CharField(choices=[('', 'Выберите уровень обучения'), ('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура')], max_length=50, null=True),
        ),
    ]
