# Generated by Django 4.2.1 on 2023-05-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_alter_student_edu_field_alter_student_edu_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entrance_agreement',
            field=models.FileField(null=True, upload_to='entrance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='info_check_agreement',
            field=models.FileField(null=True, upload_to='info'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport',
            field=models.FileField(null=True, upload_to='passport'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_translation',
            field=models.FileField(null=True, upload_to='passport_n'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_diploma',
            field=models.FileField(null=True, upload_to='diploma'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_diploma_translation',
            field=models.FileField(null=True, upload_to='diploma_n'),
        ),
    ]
