# Generated by Django 4.2.1 on 2023-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_alter_student_entrance_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='citizenship',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
