# Generated by Django 4.2.1 on 2023-05-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_student_slug_customuser_student_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
