# Generated by Django 4.2.1 on 2023-05-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_customuser_alter_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
