# Generated by Django 4.2.1 on 2023-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_alter_student_username_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
