# Generated by Django 4.2.1 on 2023-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_student_address_desc_student_citizenship_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='checked',
            field=models.CharField(choices=[('Checked', 'Checked'), ('Checked Once', 'Checked Once'), ('Unchecked', 'Unchecked')], default='Unchecked', max_length=50),
        ),
    ]
